# Generated by Django 3.1.6 on 2021-02-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20210211_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='User_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
