# Generated by Django 3.1.6 on 2021-02-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_offer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='User_id',
            field=models.CharField(max_length=500),
        ),
    ]
